export const ProductsData = [
  {
    id: 1,
    name: "Syltherine",
    description: "Stylish cafe chair",
    full_price: "Rp 2.500.000",
    discount_price: "Rp 3.500.000",
    image: require("../../assets/sylthe.png"),
  },
  {
    id: 2,
    name: "Leviosa",
    description: "Stylish cafe chair",
    full_price: "Rp 2.500.000",
    image: require("../../assets/leviosa.png"),
  },
  {
    id: 3,
    name: "Lolito",
    description: "Luxury big sofa",
    full_price: "Rp 7.000.000",
    discount_price: "14.000.000",
    image: require("../../assets/lolito.png"),
  },
  {
    id: 4,
    name: "Respira",
    description: "Outdoor bar table and stool",
    full_price: "Rp 5.000.000",
    image: require("../../assets/respira.png"),
  },
  {
    id: 5,
    name: "Grifo",
    description: "night Lamp",
    full_price: "Rp 1.500.000",
    image: require("../../assets/grifo.png"),
  },
  {
    id: 6,
    name: "Muggo",
    description: "Small mug",
    full_price: "150.000",
    image: require("../../assets/muggo.png"),
  },
  {
    id: 7,
    name: "Pingky",
    description: "cute bed set",
    full_price: "7.000.000",
    discount_price: "14.000.000",
    image: require("../../assets/pingky.png"),
  },
  {
    id: 8,
    name: "Potty",
    description: "Minimalist flower pot",
    full_price: "500.000",
    image: require("../../assets/potty.png"),
  },
];
