export const StreamData = [
  {
    id: 1,
    name: "John Doe",
    description: "Wordpress & Plugin Tutor",
    image: require("../../assets/img-1.jpg"),
    students: "100k",
    courses: "15",
  },
  {
    id: 2,
    name: "Jassica",
    description: "Language Learning Coach, Writer, Online Tutor",
    image: require("../../assets/img-2.jpg"),
    students: "14k",
    courses: "11",
  },
  {
    id: 3,
    name: "Edutus+",
    description: "Head of Data Science, Pierian Data Inc",
    image: require("../../assets/img-9.jpg"),
    students: "1M",
    courses: "25",
  },
  {
    id: 4,
    name: "Joginder Singh",
    description: "Head of Data Science, Pierian Data Inc",
    students: "1M",
    courses: "25",
    image: require("../../assets/img-4.jpg"),
  },
  {
    id: 5,
    name: "Zoena",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-5.jpg"),
  },
  {
    id: 6,
    name: "Albert Dua",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-6.jpg"),
  },
  {
    id: 7,
    name: "Ridhima",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-7.jpg"),
  },
  {
    id: 8,
    name: "Amritpal",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-8.jpg"),
  },
  {
    id: 9,
    name: "Jimmy",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-3.jpg"),
  },
  {
    id: 10,
    name: "Quin Bachelor",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-10.jpg"),
  },
  {
    id: 11,
    name: "Eli Nitoli",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-11.jpg"),
  },
  {
    id: 12,
    name: "Jaison Bachelor",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-12.jpg"),
  },
  {
    id: 13,
    name: "Farhat Ameen",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-13.jpg"),
  },
  {
    id: 14,
    name: "Kyle Piew",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-14.jpg"),
  },
  {
    id: 15,
    name: "Kerstin Cable",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-15.jpg"),
  },
  {
    id: 16,
    name: "Josh Porlia",
    description: "Head of Data Science, Pierian Data Inc",
    students: "100k",
    courses: "15",
    image: require("../../assets/img-16.jpg"),
  },
  {
    id: 17,
    name: "Joginder Singh",
    description: "Web Developer ,Designer and Teacher",
    students: "615k",
    courses: "12",
    image: require("../../assets/img-17.jpg"),
  },
];
