export const FeaturedData = [
  {
    id: 1,
    image: require("../../assets/featured1.jpg"),
    views: "109k",
    time: "15 days ago",
    course_name: "Complete Python Bootcamp: Go from zero to hero in Python 3",
    description: "Web Development | Python",
    instructor_name: "John Doe",
    price: "$10",
  },
  {
    id: 2,
    image: require("../../assets/featured2.jpg"),
    views: "5M",
    time: "15 days ago",
    course_name: "The Complete JavaScript Course 2020: Build Real Projects!",
    description: "Development | JavaScript",
    instructor_name: "Jassica William",
    price: "$10",
  },
  {
    id: 3,
    image: require("../../assets/featured3.jpg"),
    views: "1M",
    time: "15 days ago",
    course_name: "Beginning C++ Programming - From Beginner to Beyond",
    description: "Development | C++",
    instructor_name: "Joginder Singh",
    price: "$13",
  },
  {
    id: 4,
    image: require("../../assets/featured4.jpg"),
    views: "153k",
    time: "3 months ago",
    course_name: "The Complete Digital Marketing Course - 12 Courses in 1",
    description: "Digital Marketing | Marketing",
    instructor_name: "Poonam Verma",
    price: "$12",
  },
  {
    id: 5,
    image: require("../../assets/featured5.jpg"),
    views: "53k",
    time: "14 days ago",
    course_name: "Microsoft Excel - Excel from Beginner to Advanced",
    description: "Office Productivity | Excel",
    instructor_name: "Rock William",
    price: "$6",
  },
  {
    id: 6,
    image: require("../../assets/featured6.jpg"),
    views: "253k",
    time: "10 days ago",
    course_name: "Angular 8 - The Complete Guide (2020 Edition)",
    description: "Development | Angular",
    instructor_name: "John Doe",
    price: "$15",
  },
  {
    id: 7,
    image: require("../../assets/featured7.jpg"),
    views: "109k",
    time: "15 days ago",
    course_name: "WordPress for Beginners: Create a Website Step by Step",
    description: "Design | Wordpress",
    instructor_name: "Sabnam Singh",
    price: "$13",
  },
  {
    id: 8,
    image: require("../../assets/featured8.jpg"),
    views: "196k",
    time: "1 month ago",
    course_name: "CSS - The Complete Guide 2020 (incl. Flexbox, Grid & Sass)",
    description: "Design | CSS",
    instructor_name: "Jashanpreet Singh",
    price: "$10",
  },
];
