export const Newest_dData = [
  {
    id: 1,
    image: require("../../assets/newest1.jpg"),
    views: "15",
    time: "10 min ago",
    course_name: "Build Responsive Real World Websites with HTML5 and CSS3",
    description: "Development | CSS",
    instructor_name: "John Doe",
    price: "$4",
    duration: "12 hours",
  },
  {
    id: 2,
    image: require("../../assets/newest2.jpg"),
    views: "5",
    time: "15 Min ago",
    course_name: "The Complete JavaScript Course 2020: Build Real Projects!",
    description: "Development | JavaScript",
    instructor_name: "Jassica William",
    price: "$5",
    duration: "28 hours",
  },
  {
    id: 3,
    image: require("../../assets/newest3.jpg"),
    views: "25",
    time: "2 Hour ago",
    course_name: "The Complete Front-End Web Development Course!",
    description: "Development | Web Development",
    instructor_name: "Joginder Singh",
    price: "$9",
    duration: "12 hours",
  },
  {
    id: 4,
    image: require("../../assets/newest4.jpg"),
    views: "15",
    time: "6 Hours ago",
    course_name: "Ethical Hacking - Most Advanced Level Penetration Testing",
    description: "IT & Software | Ethical Hacking",
    instructor_name: "Poonam Verma",
    price: "$10",
    rating: "5.0",
    duration: "1 hour",
  },
  {
    id: 5,
    image: require("../../assets/newest5.jpg"),
    views: "45",
    time: "20 hours ago",
    course_name: "Advanced CSS and Sass: Flex-box, Grid, Animations and More!",
    description: "Development | Sass",
    instructor_name: "Rock William",
    price: "$6",
    rating: "3.5",
    duration: "28 hours",
  },
  {
    id: 6,
    image: require("../../assets/newest6.jpg"),
    views: "20",
    time: "1 day ago",
    course_name: "The Complete Node.js Developer Course (3rd Edition)",
    description: "Development | Node.js",
    instructor_name: "John Doe",
    price: "$3",
    duration: "30 hours",
  },
  {
    id: 7,
    image: require("../../assets/newest7.jpg"),
    views: "200",
    time: "4 days ago",
    course_name: "WordPress Development - Themes, Plugins & Gutenberg",
    description: "Design | Wordpress",
    instructor_name: "Joy dua",
    price: "$14",
    rating: "5.0",
    duration: "21 hours",
  },
  {
    id: 8,
    image: require("../../assets/newest8.jpg"),
    views: "11",
    time: "5 days ago",
    course_name: "Vue JS 2 - The Complete Guide (incl. Vue Router & Vuex)",
    description: "Design | Vue JS",
    instructor_name: "Manreet Kaur",
    price: "$10",
    duration: "22 hours",
  },
];
